---
version: '3'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.8.68.0/22
services:
  freqtrade:
    image: freqtradeorg/freqtrade:2025.4
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: MM_ADV
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./scripts:/freqtrade/scripts"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:3004:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Market_Making
